import { ServiceAction } from '@root/prisma/services-data/services.dto';

export const githubCreateAnIssueData: ServiceAction = {
  class_name: 'GithubCreateAnIssueExecutor',
  http_requests: {
    method: 'POST',
    endpoint: '',
    description: 'Create an issue on a specific github personal repository',
  },
  name: 'Create an issue',
  description: 'Create an issue on a specific github personal repository',
  require_connection: true,
  fields: {
    owner: {
      key: 'owner',
      required: true,
      type: 'string',
      select_options: [],
      field_name: 'Repository owner',
      default_value: '',
      placeholder: 'AREA-REN',
      field_order: 5,
      validation_rules: {},
      is_active: true,
    },
    repository: {
      key: 'repository',
      required: true,
      type: 'string',
      select_options: [],
      field_name: 'Repository name',
      default_value: '',
      placeholder: 'repository-name',
      field_order: 4,
      validation_rules: {},
      is_active: true,
    },
    title: {
      key: 'title',
      required: true,
      type: 'string',
      select_options: [],
      field_name: 'Title of the issue',
      default_value: '',
      placeholder: 'My new issue',
      field_order: 3,
      validation_rules: {},
      is_active: true,
    },
    content: {
      key: 'content',
      required: false,
      type: 'string',
      select_options: [],
      field_name: 'Content of the issue',
      default_value: '',
      placeholder: 'Type your issue description here...',
      field_order: 2,
      validation_rules: {},
      is_active: true,
    },
    assignees: {
      key: 'assignees',
      required: true,
      type: 'string',
      select_options: [],
      field_name: 'Assignees (separated by commas)',
      default_value: '',
      placeholder: 'nitrached,eliestroun14,AymericJM,Smoulmouc,nl1x',
      field_order: 1,
      validation_rules: {},
      is_active: true,
    },
    labels: {
      key: 'labels',
      required: true,
      type: 'string',
      select_options: [],
      field_name: 'Labels (separated by commas)',
      default_value: '',
      placeholder: 'feature,web,suggestion',
      field_order: 0,
      validation_rules: {},
      is_active: true,
    },
  },
  variables: [
    { name: 'IssueTitle' },
    { name: 'IssueContent' },
    { name: 'IssueAssignees' },
    { name: 'IssueLabels' },
    { name: 'RepositoryName' },
    { name: 'RepositoryOwner' },
    { name: 'RepositoryUrl' },
  ],
  is_active: true,
  created_at: new Date(Date.now()),
  updated_at: new Date(Date.now()),
};
