version: '3.8'

services:
  database:
    image: mysql:8-debian
    volumes:
      - area_database_volume:/var/lib/mysql
    ports:
      - "3406:3306"
    networks:
      - area_database_network
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  dashboard:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - area_database_network
    env_file:
      - .env
    depends_on:
      - database

networks:
  area_database_network:

volumes:
  area_database_volume:
