import { ServiceAction } from '@root/prisma/services-data/services.dto';

export const oneDriveUploadFileData: ServiceAction = {
  class_name: 'OneDriveUploadFileExecutor',
  http_requests: {
    method: 'PUT',
    endpoint: '/v1.0/me/drive/root:/{filename}:/content',
    description: 'Upload a file to OneDrive',
  },
  name: 'Upload File',
  description: 'Upload a file to OneDrive',
  require_connection: true,
  fields: {
    file_content: {
      key: 'file_content',
      field_name: 'File Content',
      required: true,
      type: 'string',
      default_value: '',
      placeholder: 'Enter file content or use variables from triggers',
      field_order: 0,
      is_active: true,
      select_options: [],
      validation_rules: {},
    },
    filename: {
      key: 'filename',
      field_name: 'File Name',
      required: true,
      type: 'string',
      default_value: 'new_file.txt',
      placeholder: 'Enter filename with extension (e.g., document.txt)',
      field_order: 1,
      is_active: true,
      select_options: [],
      validation_rules: {},
    },
    folder_path: {
      key: 'folder_path',
      field_name: 'Folder Path',
      required: false,
      type: 'string',
      default_value: '/',
      placeholder: 'Enter folder path (e.g., /Documents) or leave empty for root',
      field_order: 2,
      is_active: true,
      select_options: [],
      validation_rules: {},
    },
  },
  variables: [
    { name: 'file_id' },
    { name: 'file_name' },
    { name: 'file_size' },
    { name: 'download_url' },
    { name: 'upload_success' },
  ],
  is_active: true,
  created_at: new Date(Date.now()),
  updated_at: new Date(Date.now()),
};
