import { ServiceAction } from '@root/prisma/services-data/services.dto';

export const microsoftTeamsSendReactionData: ServiceAction = {
  class_name: 'MicrosoftTeamsSendReactionExecutor',
  http_requests: {
    method: 'POST',
    endpoint: '/v1.0/teams/{team-id}/channels/{channel-id}/messages/{message-id}/reactions',
    description:
      'Send a reaction to a Microsoft Teams message',
  },
  name: 'Send Reaction',
  description: 'Send a reaction to a Microsoft Teams message',
  require_connection: true,
  fields: {
    team_id: {
      key: 'team_id',
      field_name: 'Team ID',
      required: true,
      type: 'string',
      default_value: '',
      placeholder: 'Enter the Teams Team ID',
      field_order: 0,
      is_active: true,
      select_options: [],
      validation_rules: {},
    },
    channel_id: {
      key: 'channel_id',
      field_name: 'Channel ID',
      required: true,
      type: 'string',
      default_value: '',
      placeholder: 'Enter the Teams Channel ID',
      field_order: 1,
      is_active: true,
      select_options: [],
      validation_rules: {},
    },
    message_id: {
      key: 'message_id',
      field_name: 'Message ID',
      required: true,
      type: 'string',
      default_value: '',
      placeholder: 'Enter the Message ID to react to',
      field_order: 2,
      is_active: true,
      select_options: [],
      validation_rules: {},
    },
    reaction: {
      key: 'reaction',
      field_name: 'Reaction',
      required: true,
      type: 'select',
      default_value: 'like',
      placeholder: 'Choose a reaction',
      field_order: 3,
      is_active: true,
      select_options: [
        'like',
        'heart',
        'laugh',
        'surprised',
        'sad',
        'angry',
      ],
      validation_rules: {},
    },
  },
  variables: [
    { name: 'reaction_sent' },
    { name: 'reaction_type' },
  ],
  is_active: true,
  created_at: new Date(Date.now()),
  updated_at: new Date(Date.now()),
};
