import { Service } from '@root/prisma/services-data/services.dto';

export const services = {
  gmail: { name: 'Gmail', slug: 'gmail' },
  github: { name: 'Github', slug: 'github' },
  discord: { name: 'Discord', slug: 'discord' },
  teams: { name: 'Teams', slug: 'teams' },
};

export const servicesData: Service[] = [
  {
    name: 'Scheduling',
    serviceColor: '#1C1C1C',
    iconUrl: '/assets/schedule.png',
    apiBaseUrl: 'none',
    authType: 'oauth2',
    documentationUrl: 'none',
    isActive: true,
    triggers: [
      {
        class_name: 'ScheduleTrigger_EveryMinutes',
        http_requests: null,
        webhook: null,
        trigger_type: 'POLLING',
        name: 'Every minutes',
        description: 'Execute actions every minutes',
        polling_interval: 1000,
        fields: {
          seconds: {
            key: 'Seconds',
            required: true,
            type: 'number',
            select_options: [],
            field_name: 'Interval of seconds',
            default_value: '10',
            placeholder: '10',
            field_order: 0,
            validation_rules: {},
            is_active: true,
          },
        },
        variables: [
          {
            type: 'string',
            key: 'date',
            name: 'Date',
          },
        ],
        is_active: true,
        created_at: new Date(Date.now()),
        updated_at: new Date(Date.now()),
      },
    ],
    actions: [],
  },
  {
    name: services.discord.name,
    serviceColor: '#7289da',
    iconUrl: '/assets/discord.png',
    apiBaseUrl: 'https://discord.com/api',
    authType: 'oauth2',
    documentationUrl: 'https://discord.com/developers/docs/reference/',
    isActive: true,
    triggers: [],
    actions: [
      {
        http_requests: {
          description: 'Send a message.',
          method: 'POST',
          endpoint: 'https://discord.com/api/webhooks/',
        },
        class_name: 'DiscordAction_SendMessage',
        name: 'Send message',
        description: 'Send a message to Discord using a webhook.',
        fields: {
          message: {
            key: 'message',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Message',
            default_value: 'Hello from AREA!',
            placeholder: 'Your message',
            field_order: 1,
            validation_rules: {},
            is_active: true,
          },
          webhook_url: {
            key: 'webhook_url',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Webhook URL',
            default_value:
              'https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_SECRET',
            placeholder: 'Your webhook URL',
            field_order: 0,
            validation_rules: {},
            is_active: true,
          },
        },
        variables: [],
        is_active: false,
        created_at: new Date(Date.now()),
        updated_at: new Date(Date.now()),
      },
    ],
  },
  {
    name: services.github.name,
    serviceColor: '#21262d',
    iconUrl: '/assets/github.png',
    apiBaseUrl: 'https://api.github.com',
    authType: 'oauth2',
    documentationUrl: 'https://docs.github.com/en/rest/',
    isActive: true,
    triggers: [
      // {
      //   class_name: 'GithubTrigger_OnNewRepository',
      //   http_requests: null,
      //   webhook: null,
      //   trigger_type: 'WEBHOOK',
      //   name: 'On new Github Repository',
      //   description: 'Detect when a new repository is created on your profile.',
      //   polling_interval: null,
      //   fields: {
      //     owner: {
      //       key: 'owner',
      //       required: true,
      //       type: 'string',
      //       select_options: [],
      //       field_name: 'Repository Owner',
      //       default_value: 'nl1x',
      //       placeholder: 'Owner',
      //       field_order: 1,
      //       validation_rules: {},
      //       is_active: true,
      //     },
      //   },
      //   variables: [
      //     {
      //       name: 'RepositoryName',
      //       key: 'repository.name',
      //       type: 'string',
      //     },
      //   ],
      //   is_active: true,
      //   created_at: new Date(Date.now()),
      //   updated_at: new Date(Date.now()),
      // },
    ],
    actions: [],
  },
  {
    name: services.gmail.name,
    serviceColor: '#4285F4',
    iconUrl: '/assets/gmail.png',
    apiBaseUrl: 'https://gmail.googleapis.com',
    authType: 'oauth2',
    documentationUrl:
      'https://developers.google.com/workspace/gmail/api/reference/rest',
    isActive: true,
    triggers: [],
    actions: [],
  },
  {
    name: services.teams.name,
    serviceColor: '#464EB8',
    iconUrl: '/assets/teams.svg',
    apiBaseUrl: 'https://graph.microsoft.com',
    authType: 'oauth2',
    documentationUrl: 'https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0',
    isActive: true,
    triggers: [
      {
        class_name: 'TeamsTrigger_OnNewMessage',
        http_requests: null,
        webhook: null,
        trigger_type: 'POLLING',
        name: 'New message received',
        description: 'Triggers when a new message is received in a Teams channel',
        polling_interval: 30000, // Poll every 30 seconds
        fields: {
          team_id: {
            key: 'team_id',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Team ID',
            default_value: '',
            placeholder: 'Enter the Team ID',
            field_order: 0,
            validation_rules: {},
            is_active: true,
          },
          channel_id: {
            key: 'channel_id',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Channel ID',
            default_value: '',
            placeholder: 'Enter the Channel ID',
            field_order: 1,
            validation_rules: {},
            is_active: true,
          },
        },
        variables: [
          {
            type: 'string',
            key: 'message_id',
            name: 'Message ID',
          },
          {
            type: 'string',
            key: 'message_content',
            name: 'Message Content',
          },
          {
            type: 'string',
            key: 'sender_name',
            name: 'Sender Name',
          },
          {
            type: 'string',
            key: 'sender_email',
            name: 'Sender Email',
          },
          {
            type: 'string',
            key: 'created_at',
            name: 'Created At',
          },
        ],
        is_active: true,
        created_at: new Date(Date.now()),
        updated_at: new Date(Date.now()),
      },
    ],
    actions: [
      {
        http_requests: {
          description: 'Send a message to a Teams channel.',
          method: 'POST',
          endpoint: 'https://graph.microsoft.com/v1.0/teams/{team-id}/channels/{channel-id}/messages',
        },
        class_name: 'TeamsAction_SendMessage',
        name: 'Send message',
        description: 'Send a message to a Microsoft Teams channel.',
        fields: {
          team_id: {
            key: 'team_id',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Team ID',
            default_value: '',
            placeholder: 'Enter the Team ID',
            field_order: 0,
            validation_rules: {},
            is_active: true,
          },
          channel_id: {
            key: 'channel_id',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Channel ID',
            default_value: '',
            placeholder: 'Enter the Channel ID',
            field_order: 1,
            validation_rules: {},
            is_active: true,
          },
          message: {
            key: 'message',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Message',
            default_value: 'Hello from AREA!',
            placeholder: 'Your message',
            field_order: 2,
            validation_rules: {},
            is_active: true,
          },
        },
        variables: [],
        is_active: true,
        created_at: new Date(Date.now()),
        updated_at: new Date(Date.now()),
      },
      {
        http_requests: {
          description: 'Send a reaction to a Teams message.',
          method: 'POST',
          endpoint: 'https://graph.microsoft.com/v1.0/teams/{team-id}/channels/{channel-id}/messages/{message-id}/reactions',
        },
        class_name: 'TeamsAction_SendReaction',
        name: 'React to message',
        description: 'Add a reaction to a Microsoft Teams message.',
        fields: {
          team_id: {
            key: 'team_id',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Team ID',
            default_value: '',
            placeholder: 'Enter the Team ID',
            field_order: 0,
            validation_rules: {},
            is_active: true,
          },
          channel_id: {
            key: 'channel_id',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Channel ID',
            default_value: '',
            placeholder: 'Enter the Channel ID',
            field_order: 1,
            validation_rules: {},
            is_active: true,
          },
          message_id: {
            key: 'message_id',
            required: true,
            type: 'string',
            select_options: [],
            field_name: 'Message ID',
            default_value: '',
            placeholder: 'Enter the Message ID to react to',
            field_order: 2,
            validation_rules: {},
            is_active: true,
          },
          reaction: {
            key: 'reaction',
            required: true,
            type: 'select',
            select_options: [
              'like',
              'heart', 
              'laugh',
              'surprised',
              'sad',
              'angry',
            ],
            field_name: 'Reaction Type',
            default_value: 'like',
            placeholder: 'Select a reaction',
            field_order: 3,
            validation_rules: {},
            is_active: true,
          },
        },
        variables: [],
        is_active: true,
        created_at: new Date(Date.now()),
        updated_at: new Date(Date.now()),
      },
    ],
  },
];
