name: CI

on:
  push:
    branches:
      - main
      - dev
      - "feat/**"

jobs:
  build-test:
    if: github.repository == 'eliestroun14/AREA_mirror'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Check if frontend exists
        id: check-frontend
        run: |
          if [ -d "./front_end/web" ] && [ -f "./front_end/web/package.json" ]; then
            echo "frontend_exists=true" >> $GITHUB_OUTPUT
          else
            echo "frontend_exists=false" >> $GITHUB_OUTPUT
            echo "Frontend directory not found, skipping frontend steps"
          fi

      - name: Install dependencies
        if: steps.check-frontend.outputs.frontend_exists == 'true'
        run: npm install
        working-directory: ./front_end/web

      - name: Run lint
        if: steps.check-frontend.outputs.frontend_exists == 'true'
        run: npm run lint -- --ignore-pattern '**/*.spec.ts'
        working-directory: ./front_end/web

      - name: Install backend dependencies
        run: pnpm install
        working-directory: ./back_end

      - name: Run backend e2e tests
        run: pnpm test:e2e
        working-directory: ./back_end

      - name: Check if docker-compose exists
        id: check-docker
        run: |
          if [ -f "./docker-compose.yml" ] || [ -f "./docker-compose.yaml" ]; then
            echo "docker_exists=true" >> $GITHUB_OUTPUT
          else
            echo "docker_exists=false" >> $GITHUB_OUTPUT
            echo "Docker compose file not found, skipping Docker build"
          fi

      - name: Build Docker images
        if: steps.check-docker.outputs.docker_exists == 'true'
        run: docker compose build

      - name: Security scan with Trivy
        if: steps.check-docker.outputs.docker_exists == 'true'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-app:latest
          format: 'table'