  name: Mirroring
  on:
    workflow_run:
      workflows: ["CI"]
      types:
        - completed
        
  env:
    MIRROR_URL: git@github.com:EpitechPGE3-2025/G-DEV-500-REN-5-1-area-3.git


  jobs:
    mirroring:
      if: |
        github.event.workflow_run.conclusion == 'success' &&
        (
          startsWith(github.event.workflow_run.head_branch, 'feat/') ||
          github.event.workflow_run.head_branch == 'main' ||
          github.event.workflow_run.head_branch == 'dev'
        )
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url: ${{env.MIRROR_URL}}
            ssh_private_key: ${{secrets.MIRRORING2}}